import resend
from datetime import datetime
from .config import Config

resend.api_key = Config.RESEND_API_KEY

def generate_html_email(analysis_data):
    """Generates HTML content for the email."""
    if not analysis_data:
        return "<p>No analysis data available.</p>"

    themes_html = ""
    for theme in analysis_data.get('top_themes', []):
        themes_html += f"""
        <div style="margin-bottom: 20px; padding: 15px; background-color: #f9f9f9; border-radius: 8px;">
            <h3 style="margin-top: 0; color: #333;">{theme.get('title')}</h3>
            <p style="margin: 5px 0;">{theme.get('description')}</p>
            <p style="margin: 5px 0; font-size: 0.9em; color: #666;">
                Sentiment: <strong>{theme.get('sentiment')}</strong> | Impact: ~{theme.get('count')} reviews
            </p>
        </div>
        """

    quotes_html = "<ul>"
    for quote in analysis_data.get('user_quotes', []):
        quotes_html += f"<li style='margin-bottom: 10px; font-style: italic;'>\"{quote}\"</li>"
    quotes_html += "</ul>"

    actions_html = "<ul>"
    for action in analysis_data.get('action_ideas', []):
        actions_html += f"<li style='margin-bottom: 10px;'>{action}</li>"
    actions_html += "</ul>"

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max_width: 600px; margin: 0 auto; padding: 20px; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
            h2 {{ color: #34495e; margin-top: 30px; }}
            .footer {{ margin-top: 40px; font-size: 0.8em; color: #999; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Weekly Review Insights: {Config.PRODUCT_NAME}</h1>
            <p>Here is your weekly pulse on user feedback from the App Store and Google Play.</p>
            
            <h2>🔥 Top Themes</h2>
            {themes_html}
            
            <h2>🗣️ Real User Quotes</h2>
            {quotes_html}
            
            <h2>🚀 Action Ideas</h2>
            {actions_html}
            
            <div class="footer">
                Generated by AI • {datetime.now().strftime('%Y-%m-%d')}
            </div>
        </div>
    </body>
    </html>
    """
    return html_content

def send_email(analysis_json, to_email=None):
    """Sends the analysis report via email using Resend."""
    if not Config.RESEND_API_KEY:
        print("RESEND_API_KEY not set. Skipping email.")
        return None

    recipient = to_email if to_email else Config.RECIPIENT_EMAIL
    
    try:
        html_content = generate_html_email(analysis_json)
        
        params = {
            "from": Config.SENDER_EMAIL,
            "to": recipient,
            "subject": f"Weekly Insights: {Config.PRODUCT_NAME} - {datetime.now().strftime('%b %d')}",
            "html": html_content,
        }

        email = resend.Emails.send(params)
        print(f"Email sent successfully: {email}")
        return email
    except Exception as e:
        print(f"Error sending email: {e}")
        return None
